// Generated by gencpp from file msg_creator/Exercise.msg
// DO NOT EDIT!


#ifndef MSG_CREATOR_MESSAGE_EXERCISE_H
#define MSG_CREATOR_MESSAGE_EXERCISE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_creator
{
template <class ContainerAllocator>
struct Exercise_
{
  typedef Exercise_<ContainerAllocator> Type;

  Exercise_()
    : type_ex(0)  {
    }
  Exercise_(const ContainerAllocator& _alloc)
    : type_ex(0)  {
  (void)_alloc;
    }



   typedef uint8_t _type_ex_type;
  _type_ex_type type_ex;





  typedef boost::shared_ptr< ::msg_creator::Exercise_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_creator::Exercise_<ContainerAllocator> const> ConstPtr;

}; // struct Exercise_

typedef ::msg_creator::Exercise_<std::allocator<void> > Exercise;

typedef boost::shared_ptr< ::msg_creator::Exercise > ExercisePtr;
typedef boost::shared_ptr< ::msg_creator::Exercise const> ExerciseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_creator::Exercise_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_creator::Exercise_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace msg_creator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'msg_creator': ['/home/nvidia/21_hf271/TX2_main/src/msg_creator/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::msg_creator::Exercise_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_creator::Exercise_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_creator::Exercise_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_creator::Exercise_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_creator::Exercise_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_creator::Exercise_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_creator::Exercise_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ca487a1ddc49ed0ec158a356e02a3ff";
  }

  static const char* value(const ::msg_creator::Exercise_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ca487a1ddc49ed0ULL;
  static const uint64_t static_value2 = 0xec158a356e02a3ffULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_creator::Exercise_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_creator/Exercise";
  }

  static const char* value(const ::msg_creator::Exercise_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_creator::Exercise_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 type_ex\n\
";
  }

  static const char* value(const ::msg_creator::Exercise_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_creator::Exercise_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type_ex);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Exercise_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_creator::Exercise_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_creator::Exercise_<ContainerAllocator>& v)
  {
    s << indent << "type_ex: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type_ex);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_CREATOR_MESSAGE_EXERCISE_H
